/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.SalesController;
import java.awt.Color;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author melodypc
 */
public class AddProject extends javax.swing.JFrame {
    
    /**
     * Creates new form AddProject
     */
    public AddProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Project = new javax.swing.JLabel();
        projectname = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        supplierdate = new org.jdesktop.swingx.JXDatePicker();
        Contact2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        supplieraddress = new javax.swing.JTextArea();
        suppliercontactnum = new javax.swing.JTextField();
        suppliercontact = new javax.swing.JTextField();
        supplier_PO = new javax.swing.JTextField();
        Contactnum2 = new javax.swing.JLabel();
        SupplierPO = new javax.swing.JLabel();
        Address2 = new javax.swing.JLabel();
        suppliername = new javax.swing.JTextField();
        Name2 = new javax.swing.JLabel();
        supplierI = new javax.swing.JLabel();
        name2I = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Contactnum1 = new javax.swing.JLabel();
        clientdate = new org.jdesktop.swingx.JXDatePicker();
        Name1 = new javax.swing.JLabel();
        Address1 = new javax.swing.JLabel();
        ClientPO = new javax.swing.JLabel();
        client_PO = new javax.swing.JTextField();
        clientname = new javax.swing.JTextField();
        clientcontact = new javax.swing.JTextField();
        clientcontactnum = new javax.swing.JTextField();
        Contact1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientaddress = new javax.swing.JTextArea();
        name1I = new javax.swing.JLabel();
        clientI = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        itemdesc = new javax.swing.JTextField();
        drdate = new org.jdesktop.swingx.JXDatePicker();
        serialno = new javax.swing.JLabel();
        includes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inclusions = new javax.swing.JTextArea();
        dr_no = new javax.swing.JTextField();
        addItem = new javax.swing.JButton();
        serialnum = new javax.swing.JTextField();
        drnumber = new javax.swing.JLabel();
        Desc = new javax.swing.JLabel();
        Brand = new javax.swing.JLabel();
        brand = new javax.swing.JTextField();
        brandI = new javax.swing.JLabel();
        serialnumI = new javax.swing.JLabel();
        dr_noI = new javax.swing.JLabel();
        itemdescI = new javax.swing.JLabel();
        projI = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        addItem1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        itemtable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        Project.setText("Project name: ");

        projectname.setName("Project Name"); // NOI18N
        projectname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectnameActionPerformed(evt);
            }
        });
        projectname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                projectnameKeyReleased(evt);
            }
        });

        submit.setText("Submit");
        submit.setEnabled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        supplierdate.setBackground(new java.awt.Color(102, 102, 102));
        supplierdate.setFormats(dateFormat);
        supplierdate.setDate(new Date());
        supplierdate.setToolTipText("");
        supplierdate.setOpaque(true);
        supplierdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierdateActionPerformed(evt);
            }
        });

        Contact2.setText("Contact Person:");

        supplieraddress.setColumns(20);
        supplieraddress.setRows(5);
        jScrollPane2.setViewportView(supplieraddress);

        suppliercontactnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliercontactnumActionPerformed(evt);
            }
        });

        suppliercontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliercontactActionPerformed(evt);
            }
        });

        supplier_PO.setBackground(new java.awt.Color(102, 102, 102));
        supplier_PO.setForeground(new java.awt.Color(255, 255, 255));
        supplier_PO.setCaretColor(new java.awt.Color(255, 255, 255));
        supplier_PO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplier_POActionPerformed(evt);
            }
        });
        supplier_PO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                supplier_POKeyReleased(evt);
            }
        });

        Contactnum2.setText("Contact number:");

        SupplierPO.setText("Supplier P.O.:");

        Address2.setText("Supplier Address:");

        suppliername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliernameActionPerformed(evt);
            }
        });
        suppliername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                suppliernameKeyReleased(evt);
            }
        });

        Name2.setText("Supplier Name:");

        supplierI.setForeground(java.awt.Color.red);
        supplierI.setText("*");

        name2I.setForeground(java.awt.Color.red);
        name2I.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(name2I, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name2))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Address2)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(supplierI)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SupplierPO))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(supplier_PO, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Contactnum2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Contact2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suppliercontactnum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suppliercontact, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(183, 183, 183))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SupplierPO, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierI))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(supplier_PO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplierdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suppliername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Name2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name2I))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Address2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(suppliercontactnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(suppliercontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Contact2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Contactnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        Contactnum1.setText("Contact number:");

        clientdate.setBackground(new java.awt.Color(102, 102, 102));
        clientdate.setFormats(dateFormat);
        clientdate.setDate(new Date());
        clientdate.setOpaque(true);
        clientdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                clientdateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                clientdateFocusLost(evt);
            }
        });
        clientdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientdateActionPerformed(evt);
            }
        });

        Name1.setText("Client Name:");

        Address1.setText("Client Address:");

        ClientPO.setBackground(new java.awt.Color(102, 102, 102));
        ClientPO.setText("Client P.O.:");

        client_PO.setBackground(new java.awt.Color(102, 102, 102));
        client_PO.setForeground(new java.awt.Color(255, 255, 255));
        client_PO.setBorder(supplier_PO.getBorder());
        client_PO.setCaretColor(new java.awt.Color(255, 255, 255));
        client_PO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                client_POActionPerformed(evt);
            }
        });
        client_PO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                client_POKeyReleased(evt);
            }
        });

        clientname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientnameActionPerformed(evt);
            }
        });
        clientname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                clientnameKeyReleased(evt);
            }
        });

        clientcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientcontactActionPerformed(evt);
            }
        });

        clientcontactnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientcontactnumActionPerformed(evt);
            }
        });

        Contact1.setText("Contact Person:");

        clientaddress.setColumns(20);
        clientaddress.setRows(5);
        jScrollPane1.setViewportView(clientaddress);

        name1I.setForeground(java.awt.Color.red);
        name1I.setText("*");

        clientI.setForeground(java.awt.Color.red);
        clientI.setText("*");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(clientI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(ClientPO, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Address1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(name1I)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(client_PO, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clientdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Contactnum1)
                    .addComponent(Contact1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientcontactnum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Contactnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientcontactnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(clientcontact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Address1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(client_PO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clientdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClientPO)
                            .addComponent(clientI, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1I))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        itemdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemdescActionPerformed(evt);
            }
        });
        itemdesc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemdescKeyReleased(evt);
            }
        });

        drdate.setFormats(dateFormat);
        drdate.setDate(new Date());
        drdate.setToolTipText("");
        drdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drdateActionPerformed(evt);
            }
        });

        serialno.setText("Serial No.:");

        includes.setText("Inclusion(s):");

        inclusions.setColumns(20);
        inclusions.setRows(5);
        jScrollPane3.setViewportView(inclusions);

        dr_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dr_noActionPerformed(evt);
            }
        });
        dr_no.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dr_noKeyReleased(evt);
            }
        });

        addItem.setText("Add Item");
        addItem.setEnabled(false);
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });

        serialnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialnumActionPerformed(evt);
            }
        });
        serialnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                serialnumKeyReleased(evt);
            }
        });

        drnumber.setText("D.R. No.:");

        Desc.setText("Description:");

        Brand.setText("Brand:");

        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                brandKeyReleased(evt);
            }
        });

        brandI.setForeground(java.awt.Color.red);
        brandI.setText("*");

        serialnumI.setForeground(java.awt.Color.red);
        serialnumI.setText("*");

        dr_noI.setForeground(java.awt.Color.red);
        dr_noI.setText("*");

        itemdescI.setForeground(java.awt.Color.red);
        itemdescI.setText("*");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(itemdescI, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(dr_noI, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(drnumber))
                                    .addComponent(includes, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Desc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(brandI, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Brand))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(serialnumI, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(serialno)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialnum)
                            .addComponent(jScrollPane3)
                            .addComponent(itemdesc)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(dr_no)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(drdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(307, Short.MAX_VALUE)
                        .addComponent(addItem)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Brand)
                    .addComponent(brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Desc, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemdescI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(includes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialnumI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dr_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(drdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dr_noI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addItem)
                .addContainerGap())
        );

        projI.setForeground(java.awt.Color.red);
        projI.setText("*");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        addItem1.setText("Remove Item");
        addItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItem1ActionPerformed(evt);
            }
        });

        itemtable.setAutoCreateRowSorter(true);
        itemtable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand", "Desc", "Includes", "Serial#", "D.R. No.", "Date(m/d/y)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        itemtable.setAutoscrolls(false);
        itemtable.setCellSelectionEnabled(true);
        itemtable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        itemtable.setFocusable(false);
        itemtable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(itemtable);
        itemtable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        itemtable.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addItem1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addItem1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(projI)
                                .addGap(7, 7, 7)
                                .addComponent(Project)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectname, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Project, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(cancel))
                .addGap(35, 35, 35))
        );

        Project.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(870, 717));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dr_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dr_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dr_noActionPerformed

    private void serialnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialnumActionPerformed

    private void itemdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemdescActionPerformed

    private void suppliercontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliercontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliercontactActionPerformed

    private void suppliernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliernameActionPerformed

    private void supplier_POActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplier_POActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplier_POActionPerformed

    private void client_POActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_client_POActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_client_POActionPerformed

    private void projectnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectnameActionPerformed

    private void clientcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientcontactActionPerformed

    private void clientnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnameActionPerformed

    private void supplierdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_supplierdateActionPerformed

    private void drdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drdateActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
        
        String br = brand.getText();
        String desc = itemdesc.getText();
        String inclusion= inclusions.getText();
        String serial = serialnum.getText();
        String drno = dr_no.getText();
        String date = dateFormat.format(drdate.getDate());
        
        DefaultTableModel model = (DefaultTableModel) this.itemtable.getModel();
        int x = model.getRowCount();
        boolean check = false;
        while (x>0){
            if(serial.equals(model.getValueAt(x-1, 3).toString()))
                check = true;
            x--;
        }
    
        if(check==true)
            JOptionPane.showMessageDialog(this, "Serial numbers cannot be similar!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        else
            model.addRow(new Object[]{br, desc, inclusion, serial, drno, date});
        
        
        checker();
        
        
    }//GEN-LAST:event_addItemActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    SalesController home = new SalesController();
    Map client = new HashMap();
    client.put("name",this.clientname.getText());
    client.put("address", this.clientaddress.getText());
    client.put("number",this.clientcontactnum.getText());
    client.put("contact",this.clientcontact.getText());
    Map supplier = new HashMap();
    supplier.put("name",this.suppliername.getText());
    supplier.put("address", this.supplieraddress.getText());
    supplier.put("number",this.suppliercontactnum.getText());
    supplier.put("contact",this.suppliercontact.getText());
    String project = this.projectname.getText();
    String clientPO = this.client_PO.getText();
    Date cdate = this.clientdate.getDate();
    String supplierPO = this.supplier_PO.getText();
    Date sdate = this.supplierdate.getDate();
     
    DefaultTableModel model = (DefaultTableModel) this.itemtable.getModel();
    int counter = model.getRowCount();
    String[][] itemlist = new String [counter][6];
    int x = 0;
    System.out.println(counter);
    System.out.println(model.getValueAt(0,0).toString());
    while(x<counter){
        for(int y=0; y<6; y++){
        itemlist[x][y] = model.getValueAt(x,y).toString();
        }
        x++;
    }
    
    
    
    
    home.addProject(client,supplier,project,clientPO,supplierPO,itemlist,cdate,sdate);// TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelActionPerformed

    private void clientcontactnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientcontactnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientcontactnumActionPerformed

    private void suppliercontactnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliercontactnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppliercontactnumActionPerformed

    private void clientdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientdateActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_clientdateActionPerformed

    private void clientdateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientdateFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_clientdateFocusLost

    private void clientdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_clientdateFocusGained
            // TODO add your handling code here:
    }//GEN-LAST:event_clientdateFocusGained

    private void addItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItem1ActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) this.itemtable.getModel();
        int[] rows = itemtable.getSelectedRows();
        for(int i=0;i<rows.length;i++){
            model.removeRow(rows[i]-i);
        }     
        
        checker();// TODO add your handling code here:
    }//GEN-LAST:event_addItem1ActionPerformed

    private void client_POKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_client_POKeyReleased
            // TODO add your handling code here:
       checker();
        if(client_PO.getText().trim().length() <= 0){
            ClientPO.setForeground(Color.red);
            clientI.setEnabled(true);
        }
        else{
            ClientPO.setForeground(Color.black);
            clientI.setEnabled(false);
        }
    }//GEN-LAST:event_client_POKeyReleased
    DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
    private void projectnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_projectnameKeyReleased
            // TODO add your handling code here:
        checker();
        if(projectname.getText().trim().length() <= 0){
            Project.setForeground(Color.red);
            projI.setEnabled(true);
        }
        else{
            Project.setForeground(Color.black);
            projI.setEnabled(false);
        }
    }//GEN-LAST:event_projectnameKeyReleased

    private void supplier_POKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_supplier_POKeyReleased
               // TODO add your handling code here:
        checker();
        if(supplier_PO.getText().trim().length() <= 0){
            SupplierPO.setForeground(Color.red);
            supplierI.setEnabled(true);
        }
        else{
            SupplierPO.setForeground(Color.black);
            supplierI.setEnabled(false);
        }
    }//GEN-LAST:event_supplier_POKeyReleased

    private void suppliernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_suppliernameKeyReleased
        checker();
        if(suppliername.getText().trim().length() <= 0){
            Name2.setForeground(Color.red);
            name2I.setEnabled(true);
        }
        else{
            Name2.setForeground(Color.black);
            name2I.setEnabled(false);
        }     // TODO add your handling code here:
    }//GEN-LAST:event_suppliernameKeyReleased

    private void clientnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clientnameKeyReleased
        checker();
        if(clientname.getText().trim().length() <= 0){
          Name1.setForeground(Color.red);
            name1I.setEnabled(true);
        }
        else{
            Name1.setForeground(Color.black);
            name1I.setEnabled(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_clientnameKeyReleased

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void brandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_brandKeyReleased
        itemchecker();
        if(brand.getText().trim().length() <= 0){
            Brand.setForeground(Color.red);
            brandI.setEnabled(true);
        }
        else{
            Brand.setForeground(Color.black);
            brandI.setEnabled(false);
        }                                // TODO add your handling code here:
    }//GEN-LAST:event_brandKeyReleased

    private void itemdescKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemdescKeyReleased
        itemchecker();
        if(itemdesc.getText().trim().length() <= 0){
            Desc.setForeground(Color.red);
            itemdescI.setEnabled(true);
        }
        else{
            Desc.setForeground(Color.black);
            itemdescI.setEnabled(false);
        }                       // TODO add your handling code here:
    }//GEN-LAST:event_itemdescKeyReleased

    private void serialnumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_serialnumKeyReleased
        itemchecker();
        if(serialnum.getText().trim().length() <= 0){
            serialno.setForeground(Color.red);
            serialnumI.setEnabled(true);
        }
        else{
            serialno.setForeground(Color.black);
            serialnumI.setEnabled(false);
        }                             // TODO add your handling code here:
    }//GEN-LAST:event_serialnumKeyReleased

    private void dr_noKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dr_noKeyReleased
        itemchecker();
        if(dr_no.getText().trim().length() <= 0){
            drnumber.setForeground(Color.red);
            dr_noI.setEnabled(true);
        }
        else{
            drnumber.setForeground(Color.black);
            dr_noI.setEnabled(false);
        }                             // TODO add your handling code here:
    }//GEN-LAST:event_dr_noKeyReleased

    /**
     * @param args the command line arguments
     */
    private void checker(){
        DefaultTableModel model = (DefaultTableModel) this.itemtable.getModel();
        if(client_PO.getText().trim().length() > 0 && projectname.getText().trim().length() > 0 && supplier_PO.getText().trim().length() > 0
             && clientname.getText().trim().length() > 0 && suppliername.getText().trim().length() > 0 && model.getRowCount() > 0){
                submit.setEnabled(true);
               
        }
        else{
                submit.setEnabled(false); 
                
        }
    }
    private void itemchecker(){
        if(brand.getText().trim().length() > 0 && itemdesc.getText().trim().length() > 0 && serialnum.getText().trim().length() > 0
             && dr_no.getText().trim().length() > 0){
                addItem.setEnabled(true);
               
        }
        else{
                addItem.setEnabled(false); 
                
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address1;
    private javax.swing.JLabel Address2;
    private javax.swing.JLabel Brand;
    private javax.swing.JLabel ClientPO;
    private javax.swing.JLabel Contact1;
    private javax.swing.JLabel Contact2;
    private javax.swing.JLabel Contactnum1;
    private javax.swing.JLabel Contactnum2;
    private javax.swing.JLabel Desc;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Project;
    private javax.swing.JLabel SupplierPO;
    private javax.swing.JButton addItem;
    private javax.swing.JButton addItem1;
    private javax.swing.JTextField brand;
    private javax.swing.JLabel brandI;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel clientI;
    public javax.swing.JTextField client_PO;
    public javax.swing.JTextArea clientaddress;
    public javax.swing.JTextField clientcontact;
    public javax.swing.JTextField clientcontactnum;
    public org.jdesktop.swingx.JXDatePicker clientdate;
    public javax.swing.JTextField clientname;
    public javax.swing.JTextField dr_no;
    private javax.swing.JLabel dr_noI;
    public org.jdesktop.swingx.JXDatePicker drdate;
    private javax.swing.JLabel drnumber;
    private javax.swing.JLabel includes;
    private javax.swing.JTextArea inclusions;
    public javax.swing.JTextField itemdesc;
    private javax.swing.JLabel itemdescI;
    private javax.swing.JTable itemtable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel name1I;
    private javax.swing.JLabel name2I;
    private javax.swing.JLabel projI;
    public javax.swing.JTextField projectname;
    private javax.swing.JLabel serialno;
    public javax.swing.JTextField serialnum;
    private javax.swing.JLabel serialnumI;
    private javax.swing.JButton submit;
    private javax.swing.JLabel supplierI;
    public javax.swing.JTextField supplier_PO;
    public javax.swing.JTextArea supplieraddress;
    public javax.swing.JTextField suppliercontact;
    public javax.swing.JTextField suppliercontactnum;
    public org.jdesktop.swingx.JXDatePicker supplierdate;
    public javax.swing.JTextField suppliername;
    // End of variables declaration//GEN-END:variables
}
